version: "3.8"

services:
  # postgres:
  #   image: postgres:16
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  ## SQL GUI
  # adminer1:
  #   image: adminer
  #   container_name: adminer1
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - mysql

  # adminer2:
  #   image: adminer
  #   container_name: adminer2
  #   ports:
  #     - "8082:8080"
  #   depends_on:
  #     - postgres
  #     - mysql

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

  # MONGODB GUI
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "1234:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
    depends_on:
      - mongo

  ## CouchDB
  # couchdb:
  #   image: couchdb:3
  #   container_name: couchdb
  #   ports:
  #     - "5984:5984"
  #   environment:
  #     COUCHDB_USER: admin
  #     COUCHDB_PASSWORD: admin
  #   volumes:
  #     - couchdb_data:/opt/couchdb/data

volumes:
  pg_data:
  mysql_data:
  mongo_data:
  couchdb_data:
