
-- ! CREATING TABLES WITH REFERENCES -- postgres 
CREATE TABLE users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(300) NOT NULL,
  last_name VARCHAR(300) NOT NULL,
  email VARCHAR(300) NOT NULL,
  address_id INT,
  FOREIGN KEY REFERENCES addresses(id) 
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE `addresses` (
  id INT PRIMARY KEY AUTO_INCREMENT,
  street VARCHAR(300) NOT NULL,
  house_number VARCHAR(300) NOT NULL,
  city_id INT,
  FOREIGN KEY  REFERENCES cities(id) 
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE `cities`(
  id INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL
);
